# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Lint & format with Ruff
        run: |
          ruff check . --fix
          ruff format .
        continue-on-error: true  
    
      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git diff --name-only)
          if [ -n "$changes" ]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi
      
      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Apply linting and formatting changes"
        
      - name: Test with pytest
        run: pytest
